
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQkZYSEplL0pseEV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1ERXdOVFUwTURSYUZ3MHpOakF6TWprd05UVTVNRFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURvODkwajNFY2oyaVlWOHJUUG1xaCszNEtiVnpjcU9PTHBnSGhpcUJ2UGlva3RMV25KVEZGWXFDaVMKZUNUQ090Z2lVS29yV08za3paV0dXSlVsd0xwUDV6UHd3cC9Tdy9QT3IwejNVZ1Q2YXpjQ2ZDQS9lNEtnNHc5VQphdFprYmo1NWIvMW5SNEs4SGhwRWUrWWZOdFZWaVduQXpzNFdNRWRseXZwc21VNVlyNm5LMWdBdldwc04rVE1TCkpKa3J2RlVpOVdodWg0UVZBdktKVGJtRWJZai9SWXg4bXlvWGk0bFFCMExYKy9JS2QyaWhKMkdoVHcvV0FwblMKTHFqa3U2dzYxeUtkNGFFRk1qeDN0cGx5UDFubHlsTEhEZDhjNHlJWllnOHdxVHl5S0NMSERlcHZJVC9oWUxhRQpuRGtuVUdDazZDRURVT0JHVS92Yzg2RXh1ei9EQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJScTJmMUVsb2I4THQ1OHhweVBRN1J3ZzNPVW9EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlFpM2hrVzQxNQowVWQxRnlMRVp5VUo5WU1RUXJyTjVCRC91TGp2clZKdjFHb2Z5SVdOQVJYVFZrK05NTGRrTElvSnNMQnZiVlRPCjh2Y0lUdHZyM0NrSDVBa2dlYzlQaGFzU1RuSEZ0ZUgySXR0NDdMazdBaklGZEU3dURoWFVsWHBPalFhd3EvRG8Kd3paNEFXUnkxSVVORyt3U2NxZm5MeFB6bHJjTTV5ZUVkdnRNRmRnNi82VmtudHduNm9GVEsydWJmUURHWDU1MQo3ay9OZ01pdDRyaUtZQk5ObFRTd2VJOWhLQVZmQ3g2ZWg2SnN4QUZSR2psUjFEQW94Znk3VERoVVJhWmlza3VsCk9PUEFRaU9TS1lxV3NkSDZadEtpeWdsTUJnZnAxVmpWdlRrcVN1NC9yMStEYXU4RFRCMUdTY2ZZQXRsMjVEWXcKMjJ3TE84M08wMVA4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://84335e6c-4135-40a3-8415-0f985c5444d4.ap-south-1-gw.linodelke.net:443
  name: lke586391

users:
- name: lke586391-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjZKc3RxOG5qQ2prdlNjTW9GX1Rsay0wUFRsQ0kyRkZVdFJpeXlOZjRjdTQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZHhoNGMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNGMxM2RmNjYtM2I2My00Y2M5LWE4YzEtY2I4ZmQ4NDJjMDQ1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.wKRS4W9EdydRpNIrDPUJfsHXu_QrawQ2SNJv8ZIDlHu9KBqnZ8IAIEf-lS9B5kieEp7iFD-oJQryb9--o1uze5eeuC39ZmH_ZakO76CG60K9iX2Aj4o77wNiPnFo9mmKE9jzcUaySdxc-k_5jGGXAEgNuWr8JAeAT0kWqhGpam_k0uudhz8AS6H3piJlDQT2ady0Njm8iUE_zhrl_ONQ0X75R_aFnIIbfyhx_GOZ0Y5Xsj2PrJTboaWOgptnf8kaYOiM2-Fm23-Kaa_caXBJ58tHekg14ON46avfbn_uTgOlOWVgzwW9I0kY0UTyrCvB35Oj8NPsZ55OCq7UBSnu9A

contexts:
- context:
    cluster: lke586391
    namespace: default
    user: lke586391-admin
  name: lke586391-ctx

current-context: lke586391-ctx
